config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "posts#index"
  # 認証
  get    '/login',   to: "sessions#new"
  post   '/login',   to: "sessions#create"
  delete '/logout',  to: "sessions#destroy"

  resources :users, only: %i[ index show new create update destroy]
  namespace :mypage do
    resources :accounts, only: %i[ edit update ]
    resources :activities, only: %i[ index ]
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[ create edit update destroy ]
    get :search, on: :collection
  end
  resources :likes, only: %i[ create destroy ]
  resources :relationships, only: %i[ create destroy ]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  followed_id :integer          not null
#  follower_id :integer          not null
#
# Indexes
#
#  index_relationships_on_followed_id                  (followed_id)
#  index_relationships_on_follower_id                  (follower_id)
#  index_relationships_on_follower_id_and_followed_id  (follower_id,followed_id) UNIQUE
#
class Relationship < ApplicationRecord
  # class_name: 'User' 参照先をUserクラスであると明示する
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  has_one :activity, as: :subject, dependent: :destroy
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  # 一意制約を設定
  validates :follower_id, uniqueness: { scope: :followed_id }

  after_create_commit :create_activities

  private

  def create_activities
    Activity.create(subject: self, user: followed, action_type: :followed_me)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    UserMailer.followed_me(@user, current_user).deliver_later if current_user.follow(@user) && @user.notification_on_follow?
  end

  def destroy
    # Relationshipモデルよりidに対応するデータを取得し, followed_idによりuserを参照したものを取得
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/views/relationships/_follow.html.slim
= form_with url: relationships_path do |f|
  = f.hidden_field :followed_id, value: user.id
  = f.submit "フォローする", class: "btn btn-outline-primary w-120px"

app/views/relationships/_follow_area.html.slim
- if logged_in? && current_user != user
  div id="follow-area-#{user.id}"
    - if current_user.following?(user)
      = render 'relationships/unfollow', user: user
    - else
      = render 'relationships/follow', user: user

app/views/relationships/_unfollow.html.slim
/ path: relationship/:id/ relationshipのidが必要であるためactive_relationshipsよりデータを検索
= form_with url: relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete do |f|
  / cssにより通常時フォロー中, hover時フォロー解除が表示されるように設定
  / button_tagでないとうまく実装できなかった
  = button_tag type: "submit", class: "btn btn-primary active w-120px", id: "unfollow" do
    |

app/views/relationships/create.js.slim
| $("#follow-area-#{@user.id}").html("#{j(render("relationships/unfollow", user: @user))}");

app/views/relationships/destroy.js.slim
| $("#follow-area-#{@user.id}").html("#{j(render("relationships/follow", user: @user))}");