config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "posts#index"
  # 認証
  get    '/login',   to: "sessions#new"
  post   '/login',   to: "sessions#create"
  delete '/logout',  to: "sessions#destroy"

  resources :users, only: %i[ index show new create update destroy]
  namespace :mypage do
    resources :accounts, only: %i[ edit update ]
    resources :activities, only: %i[ index ]
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[ create edit update destroy ]
    get :search, on: :collection
  end
  resources :likes, only: %i[ create destroy ]
  resources :relationships, only: %i[ create destroy ]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  avatar                  :string(255)
#  crypted_password        :string(255)
#  email                   :string(255)      not null
#  notification_on_comment :boolean          default(TRUE)
#  notification_on_follow  :boolean          default(TRUE)
#  notification_on_like    :boolean          default(TRUE)
#  salt                    :string(255)
#  username                :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, length: { minimum: 4, maximum: 20 }
  validates :email, uniqueness: true

  # if: -> { new_record? || changes[:crypted_password] }
  # ユーザーがパスワード以外のプロフィール項目を更新したい場合に、パスワードの入力を省略できるようになる。
  validates :password, presence: true, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  # :active_relationships followingの中間テーブルに用いる架空テーブル
  # class_name: 'Relationship'  参照先をrelationshipクラスであることを明示する
  # foreign_key: 'follower_id'  relationshipsテーブルにアクセスするときの入り口をfollower_idとする
  has_many :active_relationships,   class_name: 'Relationship',
                                    foreign_key: 'follower_id',
                                    dependent: :destroy
  # :passive_relationships followersの中間テーブルに用いる架空テーブル
  # class_name: 'Relationship'  参照先をrelationshipクラスであることを明示する
  # foreign_key: 'followed_id'  relationshipsテーブルにアクセスするときの入り口をfollowed_id'とする
  has_many :passive_relationships,  class_name: 'Relationship',
                                    foreign_key: 'followed_id',
                                    dependent: :destroy
  # :following フォローしているユーザーを参照する架空テーブル
  # through: :active_relationships 中間テーブルを設定する
  # source: :followed 出口をfollowed_idとする
  has_many :following, through: :active_relationships,  source: :followed
  # :followers フォロワーを参照する架空テーブル
  # through: :passive_relationships 中間テーブルを設定する
  # source: :follower 出口をfollower_idとする
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :activities, dependent: :destroy

  # scope 可読性を高めるためにメソッドをまとめるために用いる
  # 登録日を新しい順に並べ変え引数の数だけ取り出すメソッド
  scope :recent, ->(count) { order(created_at: :desc).limit(count) }

  def like(post)
    likes.create(post_id: post.id)
  end

  def unlike(post)
    likes.find_by(post_id: post.id).destroy
  end

  def like?(post)
    like_posts.include?(post)
  end

  # フォローをするメソッド
  def follow(other_user)
    # following にユーザを格納することでcreateと同様の処理を実現している
    following << other_user
  end

  # フォローを外すメソッド
  def unfollow(other_user)
    # following から特定のユーザを削除する
    following.destroy(other_user)
  end

  # フォローを判定するメソッド
  def following?(other_user)
    # following に特定のユーザが含まれているか判定する
    following.include?(other_user)
  end

  # フォローしているユーザーと自身の投稿だけを取得する
  # self.followings_ids 自身がフォローしているユーザのid一覧
  # id一覧の中に自身のidを追加することで自身の投稿を取得
  def feed
    Post.where(user_id: following_ids << id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :show]

  def index
    @users = User.where.not(id: current_user.id).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to @user, notice: '新規ユーザーを登録しました。'
    else
      flash.now[:denger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザーを更新しました。'
    else
      flash.now[:denger] = 'ユーザー更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'ユーザーを削除しました'
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/views/users/_form.html.slim
.container
    h1.text-center.mb-3 = yield(:form_title)
    .row.justify-content-center
        = form_with model: @user, local: true, class: 'col-md-6 col-10' do |f|
            = render 'shared/error_messages', object: @user
            .form-group
                i.fas.fa-user.prefix.mr-1
                = f.label :username
                = f.text_field :username, class: 'form-control', placeholer: "Name"
            .form-group
                i.fas.fa-envelope.prefix.grey-text.mr-1
                = f.label :email
                = f.text_field :email, class: 'form-control', placeholder: "Email"
            .form-group
                i.fas.fa-lock.prefix.grey-text.mr-1
                = f.label :password
                = f.password_field :password, class: 'form-control', placeholder: "Password"
            .form-group
                i.fas.fa-lock.prefix.grey-text.mr-1
                = f.label :password_confirmation
                = f.password_field :password_confirmation, class: 'form-control', placeholder: "Password Confirmation"
            = button_tag type: 'submit', class: 'btn btn-raised btn-primary w-100 mt-2 mb-2' do
                i.fas.fa-user.prefix.mr-1
                = yield(:button_text)
            
            - if !logged_in?
                = link_to 'Log in?', login_path, class: 'text-muted'

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between.pb-3.border-bottom
  = link_to user_path(user) do
    = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
    = user.username
  = render 'relationships/follow_area', user: user

app/views/users/edit.html.slim
- provide(:form_title, 'Edit')
- provide(:button_text, 'Update')
= render 'form'

app/views/users/index.html.slim
.container
    .row.d-flex.justify-content-center
        .col-lg-6.col-12
            .users-box
                .card
                    .card-body
                        = render @users
                        = paginate @users

app/views/users/new.html.slim
- provide(:form_title, 'Sign up')
- provide(:button_text, 'Signup')
= render 'form'

app/views/users/show.html.slim
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          .user.mb-3.d-flex.justify-content-between
            = link_to user_path(@user) do
              - if @user.avatar.present?
                = image_tag @user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
              - else
                = image_tag @user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
              = @user.username
            - if current_user == @user
              = link_to '通知一覧', mypage_activities_path, class: 'btn btn-outline-primary ml-auto'
              = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-outline-primary ml-3'
              = link_to '通知設定', edit_mypage_notification_setting_path, class: 'btn btn-outline-primary ml-3'
            - else
              = render 'relationships/follow_area', user: @user
          hr
          .row
            = render partial: 'posts/thumbnail_post', collection: @user.posts