config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "posts#index"
  # 認証
  get    '/login',   to: "sessions#new"
  post   '/login',   to: "sessions#create"
  delete '/logout',  to: "sessions#destroy"

  resources :users, only: %i[ index show new create update destroy]
  namespace :mypage do
    resources :accounts, only: %i[ edit update ]
    resources :activities, only: %i[ index ]
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[ create edit update destroy ]
    get :search, on: :collection
  end
  resources :likes, only: %i[ create destroy ]
  resources :relationships, only: %i[ create destroy ]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
    div class=("alert alert-#{message_type} ") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand.navbar-light.bg-light.z-index100
  = link_to "Insta Clone", root_path, class: "navbar-brand"
  = render 'posts/search_form', search_form: @search_form
  ul.navbar-nav.ml-auto
    li.nav-item
      = link_to posts_path, class: "nav-link" do
        i.fas.fa-home
    - if logged_in?
      li.nav-item
        = link_to new_post_path, class: "nav-link" do
          i.far.fa-image
      li.nav-item
        .dropdown
          a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            = render 'shared/unread_badge'
          #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
            = render 'shared/header_activities'
      li.nav-item
        = link_to current_user, class: "nav-link" do
          i.fas.fa-user.prefix.mr-1
      li.nav-item
        = link_to "ログアウト", logout_path, method: :delete, class: "nav-link"
    - else
      li.nav-item
        = link_to "ログイン", login_path, class: "nav-link"

app/views/shared/_header_activities.html.slim
- if current_user.activities.present?
  - current_user.activities.recent(10).each do |activity|
    = render "mypage/activities/#{activity.action_type}", activity: activity
  - if current_user.activities.count > 10
    = link_to 'すべてみる', mypage_activities_path, class: 'dropdown-item justify-content-center'
- else
  .dropdown-item
    | お知らせはありません

app/views/shared/_unread_badge.html.slim
- if current_user.activities.unread.count > 0
  span.badge.badge-warning.navbar-badge.position-absolute.rounded-circle style='top: 0; right:0;'
    = current_user.activities.unread.count