config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "posts#index"
  # 認証
  get    '/login',   to: "sessions#new"
  post   '/login',   to: "sessions#create"
  delete '/logout',  to: "sessions#destroy"

  resources :users, only: %i[ index show new create update destroy]
  namespace :mypage do
    resources :accounts, only: %i[ edit update ]
    resources :activities, only: %i[ index ]
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[ create edit update destroy ]
    get :search, on: :collection
  end
  resources :likes, only: %i[ create destroy ]
  resources :relationships, only: %i[ create destroy ]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  images     :json             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :user
  mount_uploaders :images, PostImageUploader

  validates :images, presence: true
  validates :body, presence: true, length: { maximum: 100 }

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_one :activity, as: :subject, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: %i[index show search]

  def index
    @posts = if current_user
               current_user.feed.order(created_at: :desc).page(params[:page])
             else
               Post.all.order(created_at: :desc).page(params[:page])
             end
    @users = User.recent(5)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: '新規投稿を作成しました.'
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: '投稿を編集しました.'
    else
      render :edit
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def search
    @posts = @search_form.search.includes(:user).page(params[:page])
    # binding pry
  end

  private

  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/views/posts/_form.html.slim
= form_with model: @post, local: true do |f|
    = render 'shared/error_messages', object: @post
    .form-group
        = f.label :images
        = f.file_field :images, multiple: true, class: 'form-control'
        - @post.images.each do |image|
            = image_tag image.url, size: '100x100'
    .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'
    = button_tag "登録する", type: 'submit', class: 'btn btn-raised btn-primary w-100 mt-2 mb-2'

app/views/posts/_post.html.slim
.card.mb-5.post
    .card-header
        .d-flex.align-items-center
            = image_tag 'profile-placeholder.png', size: "40x40", class: "rounded-circle mr-1"
            = link_to post.user.username, post.user
            - if post.user == current_user
                .ml-auto
                    = link_to post, method: :delete do
                        i.fas.fa-trash-alt
                    = link_to edit_post_path(post) do
                        i.fas.fa-edit.ml-2
            - elsif current_user
                .ml-auto
                    = render('likes/like', post: post)
    = link_to post do
		.swiper-container
			.swiper-wrapper
				- post.images.each do |image|
					.swiper-slide
						= image_tag image.url, class: "card-img-top"
			.swiper-pagination
    .card-body
        .card-text
            = post.body

app/views/posts/_search_form.html.slim
= form_with model: search_form, url: search_posts_path, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
  = f.search_field :body, class: 'form-control mr-sm-2', placeholder: '本文'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3.thumbnail_post
  = link_to thumbnail_post do
    .swiper-container
			.swiper-wrapper
				- thumbnail_post.images.each do |image|
					.swiper-slide.thumbs
						= image_tag image.url
      

app/views/posts/edit.html.slim
= render 'form'

app/views/posts/index.html.slim
.container
  .row
    .col-lg-8.col-12
      - if @posts.present?
        = render @posts
        = paginate @posts
      - else
        .text-center.mb-5 投稿がありません
    .col-lg-4.col-12
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr-1'
          = link_to current_user.username, user_path(current_user)
      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            = render @users
          .card-footer
            = link_to "すべて見る", users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          = render 'form'

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.card.post-show
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: "card-img-top"
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .row.no-gutters
        .col-2
          = image_tag @post.user.avatar.url, size: "40x40", class: "rounded-circle mr-1"
        .col-10
          .d-flex.align-items-center.h-100
            = link_to @post.user.username, user_path(@post.user)
            .ml-auto
              - if @post.user == current_user
                = link_to @post, method: :delete do
                  i.fas.fa-trash-alt
                = link_to edit_post_path(@post) do
                    i.fas.fa-edit.ml-2
              - elsif current_user
                = render('likes/like', post: @post)
    hr.m-0
    .post-body.p-3 id='comments'
      .row.no-gutters
        .col-2
          = image_tag @post.user.avatar.url, size: "40x40", class: "rounded-circle mr-1"
        .col-10
          = @post.body
      hr
      = render @comments
    hr.m-0
    .post-comment.p-3
      = form_with model: [@post, @comment], remote: true, class: 'form-inline mb-0' do |f|
        = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
        = f.submit '投稿', class: 'btn btn-primary btn-raised'
#modal-container